# Deploy Flask backend to Azure Web App

name: Deploy Flask backend to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: /backend/artifacts

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Install Python dependencies
      #   run: |
      #     cd backend
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: Start Gunicorn server
        run: |
          gunicorn -b :8000 backend.app:app &
          sleep 3  # Allow time for server to start

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8670AB091BB1451FBAB6AE0B60DA6310 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1B56FB80CD17441B9C22558FC7F5B33C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0C0D3CE3700D4E3AA6D5101E70198705 }}

      - name: Download backend artifact
        uses: actions/download-artifact@v2
        with:
          name: backend

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'boyaslacatalana'
          slot-name: 'Production'
          package: ${{ github.workspace }}/backend
