name: Build and deploy Node.js and Python apps to Azure Web App - boyaslacatalana

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Frontend (Node.js) build
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Set up environment variables
        run: echo "REACT_APP_GOOGLE_MAPS_API_KEY=${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}" >> .env.production

      - name: npm install, build, and test
        run: |
          npm install
          CI=false npm run build --if-present
          npm run test --if-present

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: ./build

      # Backend (Python Flask) build
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload backend artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend

      - name: Download backend artifact
        uses: actions/download-artifact@v2
        with:
          name: backend

      - name: Start Gunicorn server
        run: |
          cd backend
          gunicorn -b :8000 backend.app:app &
          sleep 3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8670AB091BB1451FBAB6AE0B60DA6310 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1B56FB80CD17441B9C22558FC7F5B33C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0C0D3CE3700D4E3AA6D5101E70198705 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'boyaslacatalana'
          slot-name: 'Production'
          packages: |
            ${{ github.workspace }}/**
